### ISSUE TITLE
Doesn't seem to work with French Client

### ISSUE THREAD

**Issue by SveRKeR92** [Eisenhuth/dalamud-nael#7]
Hi there, ty for the nice plugin ! 

Wanted to try it with French game language but didn't manage to get any of the quotes call appear in chat.
Tried to enable/disable
Also the test command is working fine.

Any idea ? Maybe there is somewhere with error logs that could help idk.

Cheers

**Comment by Eisenhuth** [comment]
I just released an update that _should_ fix this, please let me know if it's now working for you

**Comment by SveRKeR92** [comment]
Hey, just installed last version, test command changed from showing IN > OUT to the full Nael quote
Didn't seem to change anything in fight though

Here is a screenshot if you want to see 

![image](https://github.com/Eisenhuth/dalamud-nael/assets/70761787/4216f38a-5200-47e4-af89-d089b0f92319)

Upper part is testing quotes and down is in fight quotes


EDIT : My bad, looks like it was disabled 😨  will check again in the next days and will keep you updated

**Comment by Eisenhuth** [comment]
I just pushed another version changing the French quotes to also include the space before the exclamation marks (they were not present in the API), which should fix the issue.

Thank you for bringing this to my attention, please let me know if it's working for you.

**Comment by SveRKeR92** [comment]
Hi hi, tried again today, didn't seem to fix it sadly

![image](https://github.com/Eisenhuth/dalamud-nael/assets/70761787/ba481343-ae4e-4f30-8796-8a485d0deeb5)

First lines are /nael test command  and the rest is Nael speaking during the fight

I made sure plugin was enabled this time :D

**Comment by Eisenhuth** [comment]
could you maybe copy/paste the chat messages that aren't working? there must be something super small that's different between them, maybe a trailing space at the very end after the exclamation mark? 

all the lines that I'm comparing against are in this file: https://github.com/Eisenhuth/dalamud-nael/blob/master/nael/nael/NaelQuotes.json , if they don't match the quote that is in there exactly it doesn't work

**Comment by SveRKeR92** [comment]
I checked the quotes with the ones from the JSON and they are indeed the same (presuming there is no trailing space)

I am not in the game anymore to try, so I checked the logs returned from ACT, 
Looks like the space we see in chat is only shown in the user interface.
By that I mean that in my chat I would see a space before each "!"
But in ACT logs they don't.

For example :

> 2023-11-17T23:08:24.0000000+01:00|0044|Nael deus Darnus|Du haut des cieux, je vais descendre pour conquérir!|7890e51466eab545

> 2023-11-17T22:51:11.0000000+01:00|0044|Nael deus Darnus|Ô lune! Éclaire la voie de la domination!|bb453f4c2eb6d42c

> 2023-11-17T22:59:46.0000000+01:00|0044|Nael deus Darnus|Baignez dans la bénédiction de la lune incandescente!|db73623fd45a7c00

Would maybe make the difference ?
Also thank you for taking the time to try and figure this out :D 

Won't be able to test on saturday but surely sunday evening

**Comment by Eisenhuth** [comment]
I was hoping that pulling the quotes directly from `xivapi.com/NpcYell/` would be enough, but as we've seen initially that doesn't quite work, at least for French - and since you are no doubt not the only user with this type of issue I'd like to fix it as soon as possible. 

without being able to test it myself, I would need the exact chat message from Nael. Maybe we'll figure out what's going wrong between the texts from the API, the texts in-game and what's up with the texts in ACT

![image](https://github.com/Eisenhuth/dalamud-nael/assets/47415874/465ace9f-762c-4b0e-bc26-de54fd82ebfc)
![image](https://github.com/Eisenhuth/dalamud-nael/assets/47415874/426ac971-46a4-496c-99d5-10c40ddd1646)

as we can see here the ACT log also removes the line break that is present in the English original, so I can't really trust ACT not to remove other things as well, the only reliable source in this case is the in-game message, and then I'll try to apply whatever is going on there to the texts in the .json which should then hopefully fix it

**Comment by SveRKeR92** [comment]
Went in to check the quotes and they don't have a whitespace or anything at the end.
Figured some of my copy had a "line break" when it was the last dialogue in chat (not sure if we can count that as a line break)

Also here are the few quotes I had in my clipboard before my game crashed xD

Nael deus Darnus : Ô lune ! Éclaire la voie de la domination !
[0:52] Nael deus Darnus : Que l'incandescence de la lune brûle mes ennemis !

Baignez dans la bénédiction de la lune incandescente !
[0:53] Nael deus Darnus : Des cieux je vais descendre et révérer la lune !

Du haut des cieux, je vais descendre pour conquérir !
Supernova, brille de tout ton feu et irradie la terre rougie !
[0:52] Nael deus Darnus : La voie marquée par l'incandescence mène à la domination !

Could it be that there is a space before the ":" too ? 
As I can see from you screenshot, having game in French adds a space after the name of the speaker
Think it is making a diff here ?

**Comment by Eisenhuth** [comment]
I just pushed _yet another version_ (tm), this time instead of looking for exact matches it's looking for the _best match_, which should deal with any small differences in the text itself.

If it's _still_ not working after this I'm running out of ideas to deal with this without overengineering it massively.

**Comment by SveRKeR92** [comment]
Hi hi, just wanna say it is looking perfectly good now
![image](https://github.com/Eisenhuth/dalamud-nael/assets/70761787/95c41435-8262-4faf-bcd4-8acb4c1aeef3)

Only weird that the IN > OUT is displayed twice (and exclamation marks at the end of quotes), otherwise it works perfectly fine !

**Comment by Eisenhuth** [comment]
1. nice that it works _well enough_ to be functional
2. weird that it gets displayed twice on that specific one - I'll keep that on the list of things to look into
